<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="LbroServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/LbroServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/LbroServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://inm381/lbros">
    <import location="LbroService.wsdl" namespace="http://inm381/lbros"/>
    <plnk:partnerLinkType name="LbroServiceLinkType">
        <plnk:role name="LbroServiceRole" portType="ns:LbroServicePortType"/>
    </plnk:partnerLinkType>
</definitions>
