<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="VomServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/VomServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/VomServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://inm381/voms">
    <import location="VomService.wsdl" namespace="http://inm381/voms"/>
    <plnk:partnerLinkType name="VomServiceLinkType">
        <plnk:role name="VomServiceRole" portType="ns:VomServicePortType"/>
    </plnk:partnerLinkType>
</definitions>
